behaviors:
  SoccerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64            # Increased batch size
      buffer_size: 2048         # Increased buffer size
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true           # Enable normalization for more stable training
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 30000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
